### ISSUE TITLE
Problem creating postgres HA

### ISSUE THREAD

**Issue by misanche** [redhat-cop/container-native-spring-postgresql#2]
I'm getting the following issue for postgres-ha deployment, the readiness probe fails:

`Readiness probe failed: setting PGROOT to /usr/pgsql-10 chown: cannot access '/pgdata/postgres-ha': Permission denied chown: cannot access '/pgwal/postgres-ha-wal': No such file or directory psql: could not connect to server: No such file or directory Is the server running locally and accepting connections on Unix domain socket "/tmp/.s.PGSQL.5432"?`

I see the following the container is started:

```
+ mkdir -p /pgdata/postgres-ha
--
  | mkdir: cannot create directory '/pgdata': Permission denied
  | + chmod 0700 /pgdata/postgres-ha
  | User id is...
  | uid=26(postgres) gid=26(postgres) groups=26(postgres)
  | chmod: cannot access '/pgdata/postgres-ha': Permission denied
  | + [[ -v ARCHIVE_MODE ]]
  | + rm /pgdata/postgres-ha/postmaster.pid
  | rm: cannot remove '/pgdata/postgres-ha/postmaster.pid': Permission denied

```
Any input?

**Comment by garethahealy** [comment]
archiving
